apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnetgithubx 
  janus-idp.io/tekton: dotnetgithubx
  backstage.io/kubernetes-id: dotnetgithubx
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnetgithubx
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  