apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dotnetgithubx-gitops
  description: This is GitOps manifest for dotnetgithubx   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dotnetgithubx
    janus-idp.io/tekton: dotnetgithubx
    backstage.io/kubernetes-id: dotnetgithubx 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dotnetgithubx
