apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnetgithubx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnetgithubx 
  name: dotnetgithubx
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnetgithubx
    weight: 100 
