apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnetgithubx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnetgithubx 
  name: dotnetgithubx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnetgithubx 
